spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true          # Enables discovery client integration (Eureka)
          lower-case-service-id: true
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s

server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO