spring:
  application:
    name: eureka-service

server:
  port: ${SERVER_PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${SERVER_PORT:8761}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000